import { RequestCardData } from "@/components/RequestCard/RequestCard";
import { Tab } from "@/components/TabBar/TabBar";

export const ALL_REQUESTS: RequestCardData[] = [
  {
    id: "1",
    icon: "🧮",
    title: "Math Tutoring Session",
    category: "Math Tutor",
    date: "May 22, 2025",
    time: "3:00 PM",
    description: "Need help with calculus and derivatives for upcoming exam.",
    helperName: "John M.",
    helperHref: "/helpers/john-m",
    status: "confirmed",
    sessionInDays: 1,
  },
  {
    id: "2",
    icon: "✏️",
    title: "Essay Writing Consultation",
    category: "Essay Writing",
    date: "May 24, 2025",
    time: "10:00 AM",
    description: "Need help polishing my college application essay.",
    helperName: "Alexandra R.",
    helperHref: "/helpers/alexandra-r",
    status: "pending",
  },
  {
    id: "3",
    icon: "📊",
    title: "Data Encoding Project",
    category: "Data Encoding",
    date: "May 26, 2025",
    time: "Flexible",
    description: "Encode 100 rows of survey data into Google Sheets.",
    helperName: "Michael T.",
    helperHref: "/helpers/michael-t",
    status: "confirmed",
    sessionInDays: 5,
  },
  {
    id: "4",
    icon: "🎨",
    title: "Canva Presentation Design",
    category: "Graphic Design",
    date: "May 18, 2025",
    time: "Completed",
    description: "Design a 10-slide Canva deck for a business pitch.",
    helperName: "Patricia L.",
    helperHref: "/helpers/patricia-l",
    status: "completed",
    rating: 5.0,
    ratingLabel: "Great work!",
  },
  {
    id: "5",
    icon: "💻",
    title: "Web Dev Support",
    category: "Web Development",
    date: "May 10, 2025",
    time: "Completed",
    description: "Fix CSS issues on my portfolio site.",
    helperName: "Liam V.",
    helperHref: "/helpers/liam-v",
    status: "completed",
    rating: 4.8,
    ratingLabel: "Very helpful!",
  },
  {
    id: "6",
    icon: "📝",
    title: "Research Paper Review",
    category: "Academic Writing",
    date: "May 5, 2025",
    time: "Completed",
    description: "Proofread and edit a 5-page research paper.",
    helperName: "Sara M.",
    helperHref: "/helpers/sara-m",
    status: "completed",
    rating: 4.5,
    ratingLabel: "Good job!",
  },
];

export const TABS: Tab[] = [
  { key: "all", label: "All Requests" },
  { key: "active", label: "Active", count: 2 },
  { key: "pending", label: "Pending", count: 1 },
  { key: "completed", label: "Completed", count: 3 },
  { key: "cancelled", label: "Cancelled", count: 0 },
];

export const SUMMARY = {
  total: 6,
  active: 2,
  pending: 1,
  completed: 3,
  cancelled: 0,
};
